title: <p align="center"> Anushmita Mukherjee </p>
logo: /assets/img/my_photo.png
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/anushmita-mukherjee-a2090a210/">LinkedIn</a> |
  <a href="https://github.com/Anushmita17">GitHub</a>
  <br>
  A backend Software Developer Professional.
  Passionate about developing scalable, effective, and optimized solutions.
  Currently working as a Software Development Engineer in a fintech company.
  specializing in Django REST API Framework.
  Brings 2 years of fintech expertise, specializing in end-to-end solution design and development.
  Hands-on experience crafting customized fintech solutions, from design to deployment.
  <br>
  <br>
  </p>





theme: jekyll-theme-minimal
